### ISSUE TITLE
LIMES -PBM WITH AGGREGATION FUNCTION

### ISSUE THREAD

**Issue by achile23** [AKSW/LIMES-dev#102]
Hello; I need your help please.
I have a problem with using LIMES when I have to use aggregate functions and compare more than one property. I am attaching here an excerpt from my configuration file.: 

`<METRIC>
ADD(0.5*levenshtein(x.prop:property2, y.prop:property2), 0.5*levenshtein(x.prop:property3, y.prop:property3))
</METRIC>`

In principle I must have a similarity link with this configuartion, instead I have an error message : 

 INFO [main] (PPJoinController.java:155) - Getting links ...
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(Unknown Source)
        at de.uni_leipzig.simba.controller.Parser.getTerms(Parser.java:144)
        at de.uni_leipzig.simba.controller.Parser.<init>(Parser.java:26)
        at de.uni_leipzig.simba.mapper.SimpleSetConstraintsMapper.getLinks(SimpleSetConstraintsMapper.java:67)
        at de.uni_leipzig.simba.controller.PPJoinController.run(PPJoinController.java:157)
        at de.uni_leipzig.simba.controller.PPJoinController.main(PPJoinController.java:32)

Thank you.

**Comment by kvndrsslr** [comment]
Hello, you are using an old version of limes.
Please get the latest version from this repository and see if it works.
If problems still occur, please reopen this issue.

**Comment by MSherif** [comment]
Hello again, In addition to use the latest version as @kvndrsslr  mentioned, please add a threshold at the end of each measure. Therefore, your metric should become something like ``` <METRIC> ADD(0.5*levenshtein(x.prop:property2, y.prop:property2)|0.95, 0.5*levenshtein(x.prop:property3, y.prop:property3)|0.85) </METRIC>

**Comment by achile23** [comment]
Thank you for your reply. I suggest if you do not see any disadvantage of putting the jar version of the tool directly on the project folder. This is what misled me and I downloaded an older version. I will follow the instructions for use and I will keep you informed.

**Comment by ngonga** [comment]
That purpose is served by the releases. Putting jars in project folders is generally suboptimal.

**Comment by achile23** [comment]
@MSherif When I used `<METRIC>ADD(levenshtein(x.p1, y.p1)|1, levenshtein(x.p2, y.p2)|1)</METRIC>` it worked for me, but when I used `<METRIC>ADD(0.5*levenshtein(x.p1, y.p1)|1, 0.5*levenshtein(x.p2, y.p2)|1)</METRIC>` it doesn't and I have an error message : org.aksw.limes.core.exceptions.InvalidThresholdException: Invalid 0.0.
