### ISSUE TITLE
Problem with aggregation function

### ISSUE THREAD

**Issue by achile23** [AKSW/LIMES-dev#103]
Hello;

I used the new version of LIMES but I still have a problem with the aggregation function.
When I used <METRIC>ADD(levenshtein(x.p1, y.p1)|1, levenshtein(x.p2, y.p2)|1)</METRIC> it worked for me, but when I used <METRIC>ADD(0.5*levenshtein(x.p1, y.p1)|1, 0.5*levenshtein(x.p2, y.p2)|1)</METRIC> it doesn't and I have an error message : org.aksw.limes.core.exceptions.InvalidThresholdException: Invalid 0.0.

thank you.

**Comment by MSherif** [comment]
You simply missed the `*` between the measure weight and the measure name

```ADD(0.5*levenshtein(x.p1, y.p1)|1, 0.5*levenshtein(x.p2, y.p2)|1)```
