### ISSUE TITLE
Aggregation function

### ISSUE THREAD

**Issue by achile23** [AKSW/LIMES-dev#104]
Hello;

@MSherif I have not forgotten the * on my code, it disappeared when I copied it on my message. So I repeat : 

I used the new version of LIMES but I still have a problem with the aggregation function.
When I used `ADD(levenshtein(x.p1, y.p1)|1, levenshtein(x.p2, y.p2)|1)` it worked for me, but when I used `ADD(0.5*levenshtein(x.p1, y.p1)|1, 0.5*levenshtein(x.p2, y.p2)|1)` it doesn't and I have an error message : org.aksw.limes.core.exceptions.InvalidThresholdException: Invalid 0.0.

thank you.

**Comment by MSherif** [comment]
That works for me, Could you please attach the whole specs file

**Comment by achile23** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>
<PREFIX>
<NAMESPACE>http://www.w3.org/1999/02/22-rdf-syntax-ns#</NAMESPACE>
<LABEL>rdf</LABEL>
</PREFIX>
<PREFIX>
<NAMESPACE>http://www.w3.org/2002/07/owl#</NAMESPACE>
<LABEL>owl</LABEL>
</PREFIX>
<PREFIX>
<NAMESPACE>http://model.org/</NAMESPACE>
<LABEL>prop</LABEL>
</PREFIX>
<SOURCE>
<ID>source</ID>
<ENDPOINT>C:/Users/Houssem/Documents/NetBeansProjects/Keys/keys/work/source.nt</ENDPOINT>
<VAR>?x</VAR>
<PAGESIZE>1000</PAGESIZE>
<RESTRICTION></RESTRICTION>
<PROPERTY>prop:property4</PROPERTY>
<PROPERTY>prop:property8</PROPERTY>
<TYPE>N-TRIPLES</TYPE>
</SOURCE>
<TARGET>
<ID>target</ID>
<ENDPOINT>C:/Users/Houssem/Documents/NetBeansProjects/Keys/keys/work/target.nt</ENDPOINT>
<VAR>?y</VAR>
<PAGESIZE>1000</PAGESIZE>
<RESTRICTION></RESTRICTION>
<PROPERTY>prop:property4</PROPERTY>
<PROPERTY>prop:property8</PROPERTY>
<TYPE>N-TRIPLES</TYPE>
</TARGET>
<METRIC>
ADD ( 0.5*Levenshtein (x. prop:property4 , y. prop:property4)|1, 0.5*Levenshtein (x. prop:property8 , y. prop:property8)|1)
</METRIC>
<ACCEPTANCE>
<THRESHOLD>1.0</THRESHOLD>
<FILE>2.nt</FILE>
<RELATION>owl:sameAs</RELATION>
</ACCEPTANCE>
<REVIEW>
<THRESHOLD>1.0</THRESHOLD>
<FILE>review_2.nt</FILE>
<RELATION>owl:sameAs</RELATION>
</REVIEW>
<EXECUTION>
	<REWRITER>default</REWRITER>
	<PLANNER>default</PLANNER>
	<ENGINE>default</ENGINE>
</EXECUTION>
<OUTPUT>TAB</OUTPUT>
</LIMES>
`

**Comment by achile23** [comment]
I put an example here : https://drive.google.com/open?id=0B9keYcwmxORIUjVlLXhIMjFjYjg

**Comment by MSherif** [comment]
The review threshold should be lower than the acceptance threshold, like:

```
<ACCEPTANCE>
	<THRESHOLD>9.0</THRESHOLD>
	<FILE>2.nt</FILE>
	<RELATION>owl:sameAs</RELATION>
</ACCEPTANCE>

<REVIEW>
	<THRESHOLD>7.0</THRESHOLD>
	<FILE>review_2.nt</FILE>
	<RELATION>owl:sameAs</RELATION>
</REVIEW>
```

**Comment by achile23** [comment]
@MSherif You have closed the discussion and unfortunately I have not finished yet. When using the Livenstein distance (Not Normalized) the accepted links are those with small distances not the largest. So how to review threshold should be lower than acceptance threshold?

**Comment by MSherif** [comment]
The resulted mapping from limes is divided into 2 files based on the confidence value of the each mapping entry. Entries with a confidence value grater then the acceptance threshold are saved in the acceptance file, and entries with confidence grater than the review threshold *and less then the acceptance threshold goes* are saved in the review file. Entries with confidence lower than the review threshold are discarded.

**Comment by achile23** [comment]
On LIMES you do not implement the NormalizedLevenshteinDistance. For the simple Livenstein measure, the acceptance threshold must be the smallest, between the pairs: (aaab -aab) (aaaaab -aab), we will retain the first because the distance is smaller.

**Comment by ngonga** [comment]
Please read the manual pertaining to how Levenshtein is rewritten to a similarity. In general, I would suggest that you do read it completely as many of your questions should be answered there. If not, then please do feel free to write.

**Comment by achile23** [comment]
@ngonga I have seen the code and I have done tests, I'm giving a statement, the distance produced by Levenshtein measure on LIMES is not standardized [0: 1]. Thus, the links that must be retained are those that have small distances.

**Comment by ngonga** [comment]
Please read again. Levenshtein as implemented in LIMES is not a distance but a similarity that is indeed standardized.
