### ISSUE TITLE
ML algorithms and Execution Engine

### ISSUE THREAD

**Issue by Kleanthi** [AKSW/LIMES-dev#16]
Dear all,
if you are responsible for a ML algorithm and your algorithm requires an execution engine type and a planner type, please give the config instance as parameter to your constructor. No hardcoded engines and planner types. Check the Controller class for further information on how to invoke the execution engine and what parameters the (new) execute function needs. Ideally, the execution engine should interact with your ML class ONLY with the execute function and none other execute functions.

**Comment by mommi84** [comment]
`ACoreMLAlgorithm` provides getter and setter for a config.
