### ISSUE TITLE
add optional properties

### ISSUE THREAD

**Issue by MSherif** [AKSW/LIMES-dev#20]
add optional properties  to configuration file

**Comment by MSherif** [comment]
Done

**Comment by MSherif** [comment]
Now both RDF and XML configuration readers are able to read Optional properities from config files. Also, SPARQL query module fill the caches with them. Still, the integration of optional properties with all algorithms need to be checked.

**Comment by Kleanthi** [comment]
I need further explanation for this.

**Comment by MSherif** [comment]
**More explanation:**
- LIMES now is able to read optional properties form SPARQL end point and RDF files
- You could configure the optional properties in the XML configuration file using the ```<OPTIONAL_PROPERTY>``` tag as well as the the RDF configuration
- LIMES is also able to fill the cashes with the triples of the optional properties
- The configuration object contains now a new list of optional properties in addition to the list of the usual properties

**Your task:**
- If your algorithm uses only the input caches and (read properties from there) do *nothing* as the caches is already contain the triples of the optional properties in addition to the normal triples
- If your algorithm uses the properties from the configuration object some how, then you may need to update it to deal with the optional one
- Finally, if you think that your algorithm should behave differently with the optional properties. Please update it

**Comment by Kleanthi** [comment]
Thank you very much! Totally agree and it's well explained.
