### ISSUE TITLE
{XML,RDF}ConfigurationReader only works correctly with paths relative to working directory

### ISSUE THREAD

**Issue by dobraczka** [AKSW/LIMES-dev#25]
Since in the constructor both classes call      
```java   
super(System.getProperty("user.dir") + "/" + fileNameOrUri);
```
Given an absolute path the working the directory is always taken as prefix. A possible solution could be:
```java   
super(fileNameOrUri);
```
But I don't know if this would break something else.
Another option could be to make another read method which takes absolute paths

**Comment by kvndrsslr** [comment]
I would advise to remove code like above and refactor it.

Reasoning:

1. this snippet can be found in many classes 
2. it seems to be not platform-independent
3. it breaks common UX for unix / linux users who would expect to be able to pass relative paths (e.g. `./foo/bar/baz.txt` or `foo/bar/baz.txt`) as well as absolute paths (e.g. `/foo/bar/baz.txt`)

We should either use existing utility libraries or write our own utility class.

**Comment by MSherif** [comment]
Fixed by removing System.getProperty("user.dir")
