### ISSUE TITLE
GUI: entering non-URLs into "Endpoint URL" throws

### ISSUE THREAD

**Issue by yamalight** [AKSW/LIMES-dev#32]
Steps to reproduce:
1. File -> New
2. Enter "asd" into "Endpoint URL"
3. See two error dialogue boxes with stack traces

Input validation required.

**Comment by yamalight** [comment]
For some reason I get the same error when trying to use valid URL (`http://dbpedia.org`) as input.

**Comment by yamalight** [comment]
And same error when trying to use local files too.

**Comment by dobraczka** [comment]
I am unable to reproduce the bug with a valid URL or local file. But I have fixed the input validation issue.
