### ISSUE TITLE
limes.dtd is not found when using build jar 

### ISSUE THREAD

**Issue by dobraczka** [AKSW/LIMES-dev#44]
I am testing the build jar. At first I thought it was a GUI issue, but I also get it when running it in command-line. When I run ` java -jar git/LIMES-dev2/limes-core/target/limes-core-1.0.0-SNAPSHOT-jar-with-dependencies.jar -f xml path/to/example.xml` I get the following error stacktrace: http://pastebin.com/GbC3Rfse

I guess the problem is that since the limes.dtd is part of the jar the file does not exist and cannot be accessed

**Comment by kvndrsslr** [comment]
Currently, limes.dtd needs to be in the CWD when running the generated jar. It does *not* get bundled with the jar and its not intended that way. (See http://aksw.github.io/LIMES-dev/user_manual/running_limes.html )

I agree that this isn't the best solution and I would suggest modifying the XMLConfigurationReader such that limes.dtd lives under src/main/resources and users can just ignore it.  Maybe we should open a new feature request for it.

**Comment by dobraczka** [comment]
Okay, I didn't see that it should be in the CWD. Thanks! 
I also agree on changing it.
