### ISSUE TITLE
Problem with Jena and Maven packaging

### ISSUE THREAD

**Issue by dobraczka** [AKSW/LIMES-dev#45]
When running the following: `java -jar limes-core-1.0.0-SNAPSHOT-jar-with-dependencies.jar -f rdf path/to/example.ttl ` I get the following error stacktrace: 
http://pastebin.com/TAZYkNZB

A common solution for this is using the shade plugin in the pom.xml (see [here](http://stackoverflow.com/questions/36755846/jena-tdb-java-lang-exceptionininitializererror) ), but this [doesn't seem to resolve this issue every time] (http://stackoverflow.com/questions/38081684/compiling-a-class-which-depends-on-jena) . Until now I didn't have any success with it.

**Comment by kvndrsslr** [comment]
Currently, limes.dtd needs to be in the CWD when running the generated jar. It does *not* get bundled with the jar and its not intended that way. (See http://aksw.github.io/LIMES-dev/user_manual/running_limes.html )

I agree that this isn't the best solution and I would suggest modifying the XMLConfigurationReader such that limes.dtd lives under src/main/resources and users can just ignore it.  Maybe we should open a new feature request for it.

**Comment by dobraczka** [comment]
The NullPointerException is happening during system initialization. It looks like TDB
init running before ARQ init.

Jena now uses ServiceLoader for initialization. Each jena jar has a
`META-INF/services/org.apache.jena.system.JenaSubsystemLifecycle` file
which are combined to form the initializationprocess.

The Problem seems to be, that in the `META-INF/services/org.apache.jena.system.JenaSubsystemLifecycle` file the only entry is `org.apache.jena.tdb.sys.InitTDB`. If I manually add the entry `org.apache.jena.sparql.system.InitARQ` it seems to work. So basically we have to find out how we get maven to this.
