### ISSUE TITLE
RDFConfigurationWriter is not working properly

### ISSUE THREAD

**Issue by dobraczka** [AKSW/LIMES-dev#51]
I used the GUI to make a new configuration with local endpoints `resources/datasets/Persons2/person21.nt` and `resources/datasets/Persons2/person11.nt`, which was working properly in the GUI and saved it as `custom.ttl` (see [here](http://pastebin.com/piJhtLkL) ) 
After changing a few things this worked (see [fixed version](http://pastebin.com/JaQbytKE) )
The things that needed changing were: 

- `^^<http://www.w3.org/2001/XMLSchema#int> ` (or double) after, e.g. `limes:threshold` throws ` java.lang.NumberFormatException: For input string: "2^^http://www.w3.org/2001/XMLSchema#int"` so I deleted this part, which worked

- `limes:type` is missing, so this does not get recognized as local endpoint

- the properties are not in quotes so it throws `org.apache.jena.query.QueryParseException: Line 9, column 4: Unresolved prefixed name: http:`

**Comment by MSherif** [comment]
Fixed, @dobraczka please check and reopen if any of the problems persists

**Comment by dobraczka** [comment]
When making a new configuration in the GUI and saving it as .ttl the class restriction is not added as prefix. The saved configuration looks like this: http://pastebin.com/GP8fkzJH 
If I try to run it, the following error is thrown (I've also included the query):
```
 INFO [SparqlQueryModule] Query issued is 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX limes: <http://limes.sf.net/ontology/>
SELECT DISTINCT ?x ?v0
WHERE {
?x rdf:type dbo:Event .
?x rdfs:label ?v0 .
}
 INFO [SparqlQueryModule] Querying the endpoint.
 INFO [SparqlQueryModule] Getting statements 0 to -1
org.apache.jena.query.QueryParseException: Line 6, column 4: Unresolved prefixed name: rdf:type
```
