### ISSUE TITLE
Cannot use SPARQL 1.1 in Restriction

### ISSUE THREAD

**Issue by KonradHoeffner** [AKSW/LIMES-dev#6]
Restrictions are not accepted if they contain SPARQL 1.1 constructs, such as the NOT EXISTS filter.

**Comment by ngonga** [comment]
LIMES currently used SPARQL1.0 extended by property paths. This is due to most SPARQL1.1 implementations being rather dodgy. If you need SPARQL1.1, please access LIMES programmatically.
