### ISSUE TITLE
Maven build failure

### ISSUE THREAD

**Issue by rezacsedu** [AKSW/LIMES-dev#62]
Hi,

I tried to build the project on Ubuntu 14.04, however, experiencing the build failure. Here's the logs attached:
asif@ubuntu:~/LIMES-dev-1.0.0/limes-core$ mvn clean install
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3:07.227s
[INFO] Finished at: Mon Nov 07 05:06:26 PST 2016
[INFO] Final Memory: 51M/815M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (Git-Hooks-Setup) on project limes-core: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
asif@ubuntu:~/LIMES-dev-1.0.0/limes-core$ 

Please help me to get rid off the issue.

**Comment by kvndrsslr** [comment]
It seems like the error you are experiencing is caused by an error in `./git-hooks/setup.sh`. The git-hooks setup is only relevant for developers, so you can just delete the second line in `./git-hooks/setup.sh` and it should work.
