### ISSUE TITLE
Maven build fails on German locale

### ISSUE THREAD

**Issue by mwauer** [AKSW/LIMES-dev#63]
Building (mvn clean install) the current master (basically identical to release 1.0.0) results in failed tests:

> Failed tests: 
>  EvaluatorsTest.test:32->testEvaluator:56 null
>
>Tests in error: 
>  WombatCompleteTest.testSupervisedBatch:79 » StringIndexOutOfBounds String inde...
>  WombatCompleteTest.testUnsupervised:98 » StringIndexOutOfBounds String index o...
>  WombatSimpleTest.testSupervisedBatch:80 » NumberFormat For input string: "1,00...
>  WombatSimpleTest.testActive:116 » StringIndexOutOfBounds String index out of r...
>  WombatSimpleTest.testUnsupervised:99 » StringIndexOutOfBounds String index out...
>
>Tests run: 218, Failures: 1, Errors: 5, Skipped: 0

Using package shade:shade doesn't resolve this.

**Comment by MSherif** [comment]
As far as I can see you have `NumberFormat For input string: "1,00...` which mean that you have a German number setting in your system (i.e. use commas instead of floating points). Therefore, please change your setting to English number and try again.
