### ISSUE TITLE
N3 output not valid

### ISSUE THREAD

**Issue by gatemezing** [AKSW/LIMES-dev#67]
Hi,
The generated output in TTL or N3 write triples of the form:
`<http://id.insee.fr/geo/commune/10387> http://www.w3.org/2002/07/owl#sameAs <http://data.openlaw.fr/id/juri/lieujuri/389> .` ; which is supposed to be 
`<http://id.insee.fr/geo/commune/10387> <http://www.w3.org/2002/07/owl#sameAs> <http://data.openlaw.fr/id/juri/lieujuri/389>` .

There are missing "</>" in the `owl:sameAs` property. Is it a normal behavior of the serialization?
Thanks again for this awesome tool.

**Comment by Kleanthi** [comment]
Hey!
Thank you very much for your kind words, we do the best we can and we are glad you enjoy LIMES.
Yes, the missing "</>" in the owl:sameAs is normal, but thanks for mentioning it.
We will fix :)

**Comment by gatemezing** [comment]
Good to know! It will help for those having to upload directly the links generated in their triple store, without having to deal with syntax errors :)

**Comment by kvndrsslr** [comment]
Fixed in bf175ad1d07c0dfe7307a2d52c782bad700a6e87
