### ISSUE TITLE
HTTP Server mode -- status tracking

### ISSUE THREAD

**Issue by earthquakesan** [AKSW/LIMES-dev#72]
HTTP Server mode described [here](http://aksw.github.io/LIMES-dev/user_manual/server/overview.html) does not allow to track the status of LIMES job.

**Comment by kvndrsslr** [comment]
This will be implemented with the next version. Currently, the server makes use of just one thread for all requests (which is obviously bad). So implementing a request for status tracking wont do the deed. I need to implement a custom executor, working on it now.

**Comment by earthquakesan** [comment]
@kvndrsslr how can I know when the job is finished with the current version?

**Comment by kvndrsslr** [comment]
@earthquakesan As a workaround, for now you can just make a `get_result` request for some arbitrary `job_id` using curl. You will get an HTTP response only if the previously enqueued job has been finished.
I am currently unsure, to which extend status tracking should be possible. Do you think it will suffice to report job status as one of *enqueued*, *running* and *finished*?
I was thinking about also returning the log of the job for *running* and *finished*, but that seems to be hard to achieve, as I would need to somehow seperate logging for different threads.

**Comment by kvndrsslr** [comment]
Done. See updated docs for information on implemented status tracking.
