### ISSUE TITLE
HTTP Server on 1.1.0 does not work as expected

### ISSUE THREAD

**Issue by earthquakesan** [AKSW/LIMES-dev#85]
The workflow for the HTTP Server is as follows:
```
    $ docker run -d --restart=always -p 8080:8080 aksw/limes:limes-service
    $ wget https://raw.githubusercontent.com/AKSW/LIMES-dev/master/limes-core/resources/lgd-lgd.xml
    $ curl --form "fileupload=@lgd-lgd.xml" http://localhost:8080/execute
    46839272943
    $ curl http://localhost:8080/get_status?job_id=46839272943
    1
    $ curl http://localhost:8080/get_status?job_id=46839272943
    2
    $ curl http://localhost:8080/get_result/?job_id=46839272943&result_type=acceptance > results.txt
    $ cat results.txt
```

The current docker with tag "limes-service" uses "dev" branch. I tried to switch to 1.1.0, however the HTTP Server does not work as expected:
```
➜  docker-limes git:(limes-service) curl --form "fileupload=@lgd-lgd.xml" http://localhost:8080/execute
1355881261316408495
➜  docker-limes git:(limes-service) curl http://localhost:8080/get_status?job_id=1355881261316408495
<h1>404 Not Found</h1>No context found for request%
```

Please cover the case with an integration test, which should include following steps:
* Bootstrap the server (i.e. run in a thread listening to 8080 port)
* Bootstrap two SPARQL endpoints (tests can not be run against network resources, which you do not control) with 10-20 triples each (use two different ports for them, like 8081 and 8082)
* Submitting a link specification interlinking those two SPARQL endpoints, get an ID of the job, check if it is a valid ID
* Poll for status of an ID every 1 second, fail after 5-10 seconds if the job is not executed successfully
* Get the results of the job, both acceptance and review. Compare results to predefined fixtures, fail if they differ.

I will use dev branch for now for the docker image, however it might fail next week or in two weeks as people are developing there. Please investigate the issue and cover HTTP server with tests ASAP.

**Comment by kvndrsslr** [comment]
As far as I can see, 1.1.0 was derived from an older commit where the `getStatus` call wasn't implemented yet. So this is obviously just a case of miscommunication.
Please note that currently in LIMES integration tests aren't set up at all.
For sure, I agree that having them would be helpful, but they shouldn't be intermixed with unit tests. Setting them up would require an enhanced Jenkins & Maven configuration and a lot of time.
To resolve this issue, it will suffice to relocate the release to the current HEAD state of the dev-branch.

**Comment by earthquakesan** [comment]
@kvndrsslr thanks Kevin! I tested version 1.1.1, it works well. I will close this issue and make a separate one for integration tests (not urgent).
