### ISSUE TITLE
query efficiency related to multiple one-to-many PROPERTYs

### ISSUE THREAD

**Issue by ziqizhang** [AKSW/LIMES-dev#91]
Firstly huge thanks to the team in providing timely support.

This issue is somewhat related to another I closed earlier on:https://github.com/AKSW/LIMES-dev/issues/90

I understand that the first thing Limes does is to read statements from a data source and after some learning and debugging I realise that this is done in the format of a sparql query:

`SELECT DISTINCT ?x ?v0 ?v1 ?v2 ?v3`
`WHERE {`
`?x rdf:type sd:ORG .`
`?x sd:org_name ?v0 .`
`?x sd:org_member_name ?v1 .`
`?x sd:org_member_uri ?v2 .`
`?x sd:org_participated_event_uri ?v3 .`
`}`

, and the corresponding config would look like:

`<ENDPOINT>/home/zqz/Work/scholarlydata/data/limes/source_org_dataset.nt</ENDPOINT>`
		`<VAR>?x</VAR>`
		`<PAGESIZE>1000</PAGESIZE>`
		`<RESTRICTION>?x rdf:type sd:ORG</RESTRICTION>`
		`<PROPERTY>sd:org_name RENAME on</PROPERTY>`
		`<PROPERTY>sd:org_member_name RENAME omn</PROPERTY>`
		`<PROPERTY>sd:org_member_uri RENAME omu</PROPERTY>`
		`<PROPERTY>sd:org_participated_event_uri RENAME peu</PROPERTY>`

This becomes quite inefficient when for each URI, there are multiple properties to match on, and for each property there are multiple values. For example, given `sd:google` using these four properties, if we have 5 values for `sd:org_name`, 100 values for `sd:member_name`, 50 values for `sd:member_uri` and 20 values for `sd:org_participateD_event_uri`, the query will return 5x100x50x20 = 500000 statements just for this single URI. 

The class `org.aksw.limes.core.io.querySparqlQueryModule` has code between lines 106 and 120 that loops through these generated statements and caches data. This means that for this URI only, there will be 500000 iterations. As examples, I changed lines 106-120 to print progress as below.

**Code**:
`uri = soln.get(kb.getVar().substring(1)).toString();`
 `                           System.out.println(uri);//ADDED LINE`
 `                           for (int i = 0; i < kb.getProperties().size(); i++) {`
 `                               propertyLabel = kb.getProperties().get(i);`
`                                if (soln.contains("v" + i)) {`
`                                    rawValue = soln.get("v" + i).toString();`
`                                    // remove localization information, e.g. @en`
`                                    for (String propertyDub : kb.getFunctions().get(propertyLabel).keySet()) {`
 `                                       value = Preprocessor.process(rawValue,`
 `                                               kb.getFunctions().get(propertyLabel).get(propertyDub));`
`                                        cache.addTriple(uri, propertyDub, value);`
`                                        System.out.println("\tadded triple:"+propertyDub+", "+value);\\ADDED LINE`
`                                    }`
 `                               }`
 `                           }`
**Output**:
`https://w3id.org/scholarlydata/organisation/indiana-university`
`	added triple:on, indiana university`
`	added triple:omn, stephen grimes`
`	added triple:omu, https://w3id.org/scholarlydata/person/michael-conover`
`	added triple:peu, https://w3id.org/scholarlydata/event/www2012/www/2012`
`https://w3id.org/scholarlydata/organisation/indiana-university`
`	added triple:on, indiana university`
`	added triple:omn, stephen grimes`
`	added triple:omu, https://w3id.org/scholarlydata/person/michael-conover`
`	added triple:peu, https://w3id.org/scholarlydata/event/eswc2010/eswc/2010`
`https://w3id.org/scholarlydata/organisation/indiana-university`
`	added triple:on, indiana university`
`	added triple:omn, stephen grimes`
`	added triple:omu, https://w3id.org/scholarlydata/person/michael-conover`
`	added triple:peu, https://w3id.org/scholarlydata/event/www2011/www/2011`

Empirically, this causes the program to spend very long time on loading the input data. For example, on a local NT format data file that has approx 9900 triples (link can be found here: https://github.com/AKSW/LIMES-dev/issues/90) and using this muti-property, one-to-many property setting, it is currently taking >3 hours on loading the statements and still going.

I wonder if there is any easy work-around to this problem?

Thanks

**Comment by ngonga** [comment]
Hi again,

The problem you describe basically pertains to "flattening" the graph 
data for linking, which has to happen at one point I'm afraid. We chose 
to rely on the W3C standards for that purpose. Now, technically, the 
flattening should happen only once, meaning that LIMES will cache the 
flattened data (see cache folder) and load it (instead of the rerunning 
the SPARQL queries) once you used the file again. No other work-around 
is foreseen so far but suggestions are also welcome.

Best,
Axel on behalf of the LIMES team

**Comment by ziqizhang** [comment]
Thanks Axel.

A workaround I use for my application only is to adapt my NT files as well as changing slightly how LIME flattens the graph. But this is really application specific and cannot be generalised. I only hope that this can spark some other ideas.

Firstly, I adapt all my multi-valued properties to single-valued, by concatenating the values and using a special character to separate the values. Example:

`<sd:google> <sd:hasName> "Google" .`
`<sd:google> <sd:hasName> "Google Inc" .`
`<sd:google> <sd:hasName> "Google plc" .`

becomes
`<sd:google> <sd:hasName> "Google|Google Inc|Google plc" .`

This drastically reduces the number of triples for each URI and most importantly, each property only has a single value.

Secondly, change the code of `org.aksw.limes.core.io.querySparqlQueryModule` line 112 to 116 from the following:

`for (String propertyDub : kb.getFunctions().get(propertyLabel).keySet()) {`
`                                        value = Preprocessor.process(rawValue,`
`                                                kb.getFunctions().get(propertyLabel).get(propertyDub));`
`                                        cache.addTriple(uri, propertyDub, value);`
`                                    }`

to:

`for (String propertyDub : kb.getFunctions().get(propertyLabel).keySet()) {`
`                                        value = Preprocessor.process(rawValue,`
`                                                kb.getFunctions().get(propertyLabel).get(propertyDub));`
`                                         if(value.contains("|")){`
`                                            String[] values = value.split("\\|");`
`                                            for(String v: values)`
`                                                cache.addTriple(uri, propertyDub, value);`
`                                        }`
`                                    }`

, which takes care of splitting the previously concatenated values by the special character.

Effect:

on the NT file with 9860 triples, it took 6 hours to flatten because it generated > 17million statements. With this change it takes only seconds.

However, **I hope this does not break how LIMES work?**

**Comment by ngonga** [comment]
Very use-case-specific indeed but should work fine :) You might want to 
make sure that you don't reuse cached data as I'm not sure that the 
caches will behave as expected with piped strings.

Best,
Axel

**Comment by ziqizhang** [comment]
Thanks!
