### ISSUE TITLE
example machine learning training file?

### ISSUE THREAD

**Issue by ziqizhang** [AKSW/LIMES-dev#93]
Sorry to bother you with questions, but I looked in the manual as well as examples and I could not find an example to show the format of training data. 

I started with the following format which generates error: 

`<https://w3id.org/scholarlydata/organisation/l3s>	<https://w3id.org/scholarlydata/organisation/l3s-research-center>`

Error:
`[line: 2, col: 57] Triple not terminated by DOT: [IRI:https://w3id.org/scholarlydata/organisation/lias-ensma]`
`Exception in thread "main" org.apache.jena.riot.RiotException: [line: 2, col: 57] Triple not terminated by DOT: [IRI:https://w3id.org/scholarlydata/organisation/lias-ensma]`
`	at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.fatal(ErrorHandlerFactory.java:136)`

I then hardcoded the training data to be like:
`<https://w3id.org/scholarlydata/organisation/engineering-ingegneria-informatica>	<https://w3id.org/scholarlydata/organisation/engineering-ingegneria-informatica-spa>	 "2.0" .`

And it seems to be doing something as it produces some output. But I also tried another trianing data format:

`<https://w3id.org/scholarlydata/organisation/emc>	<http://www.w3.org/2002/07/owl#sameAs>	<https://w3id.org/scholarlydata/organisation/emc-corporation> .`

and this time it produces more mapping candidates.

Which is the right format?

Thanks

**Comment by MSherif** [comment]
Training data file is expected to be an RDF file in any serialization such as n-triples, turtle or RDF. Normally, you provide training data related to the relation you about to discover. For example, if you are trying to discover ```owl:sameAs``` you provide an RDF file with as many as possible correct ```owl:sameAs``` triples. such as the one you provide last.

**Comment by ziqizhang** [comment]
Thanks!
